import { Requirement } from '../types.js';

export const firstClassRequirements: Requirement[] = [
  // CAMPING AND OUTDOOR ETHICS
  {
    id: '1C-1a',
    rank: 'First Class',
    category: 'CAMPING AND OUTDOOR ETHICS',
    number: '1a',
    description: 'Since joining Scouts BSA, participate in 10 separate troop/patrol activities, at least six of which must be held outdoors. Of the outdoor activities, at least three must include overnight camping. These activities do not include troop or patrol meetings. On campouts, spend the night in a tent that you pitch or other structure that you help erect, such as a lean-to, snow cave, or tepee.',
    activityTags: ['camping'],
    setting: 'campout',
    estimatedMinutes: 0, // Tracked over time
  },
  {
    id: '1C-1b',
    rank: 'First Class',
    category: 'CAMPING AND OUTDOOR ETHICS',
    number: '1b',
    description: 'Explain the potential impacts of camping, both on the environment and on other users. Explain why the Outdoor Code and Leave No Trace principles are important for protecting the outdoors.',
    activityTags: ['camping', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },

  // COOKING
  {
    id: '1C-2a',
    rank: 'First Class',
    category: 'COOKING',
    number: '2a',
    description: 'Help plan a menu for one of the above campouts that includes at least one breakfast, one lunch, and one dinner, and that requires cooking at least two of the meals. Tell how the menu includes the foods from MyPlate or the current USDA nutritional model and how it meets nutritional needs for the planned activity or campout.',
    activityTags: ['cooking', 'planning'],
    setting: 'any',
    estimatedMinutes: 45,
  },
  {
    id: '1C-2b',
    rank: 'First Class',
    category: 'COOKING',
    number: '2b',
    description: 'Using the menu planned in First Class requirement 2a, make a list showing a budget and the food amounts needed to feed three or more youth. Secure the ingredients.',
    activityTags: ['cooking', 'planning'],
    setting: 'any',
    estimatedMinutes: 30,
  },
  {
    id: '1C-2c',
    rank: 'First Class',
    category: 'COOKING',
    number: '2c',
    description: 'Show which pans, utensils, and other gear will be needed to cook and serve these meals.',
    activityTags: ['cooking', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 20,
  },
  {
    id: '1C-2d',
    rank: 'First Class',
    category: 'COOKING',
    number: '2d',
    description: 'Demonstrate the procedures to follow in the safe handling and storage of fresh meats, dairy products, eggs, vegetables, and other perishable food products. Show how to properly dispose of camp garbage, cans, plastic containers, waste water, and other rubbish.',
    activityTags: ['cooking', 'demonstration', 'camping'],
    setting: 'either',
    estimatedMinutes: 30,
  },
  {
    id: '1C-2e',
    rank: 'First Class',
    category: 'COOKING',
    number: '2e',
    description: 'On one campout, serve as cook. Supervise your assistant(s) in using a stove or building a cooking fire. Prepare the breakfast, lunch, and dinner planned in First Class requirement 2a. Supervise the cleanup.',
    activityTags: ['cooking', 'fire-building', 'stove'],
    setting: 'campout',
    estimatedMinutes: 240,
  },

  // TOOLS
  {
    id: '1C-3a',
    rank: 'First Class',
    category: 'TOOLS',
    number: '3a',
    description: 'Discuss when you should and should not use lashings.',
    activityTags: ['lashings', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },
  {
    id: '1C-3b',
    rank: 'First Class',
    category: 'TOOLS',
    number: '3b',
    description: 'Demonstrate tying the timber hitch and clove hitch.',
    activityTags: ['knots', 'lashings', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-3c',
    rank: 'First Class',
    category: 'TOOLS',
    number: '3c',
    description: 'Demonstrate tying the square, shear, and diagonal lashings by joining two or more poles or staves together.',
    activityTags: ['lashings', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 45,
  },
  {
    id: '1C-3d',
    rank: 'First Class',
    category: 'TOOLS',
    number: '3d',
    description: 'Use lashings to make a useful camp gadget or structure.',
    activityTags: ['lashings', 'camping'],
    setting: 'campout',
    estimatedMinutes: 60,
  },

  // NAVIGATION
  {
    id: '1C-4a',
    rank: 'First Class',
    category: 'NAVIGATION',
    number: '4a',
    description: 'Using a map and compass, complete an orienteering course that covers at least one mile and requires measuring the height and/or width of designated items (tree, tower, canyon, ditch, etc.).',
    activityTags: ['compass', 'map', 'navigation', 'hiking'],
    setting: 'campout',
    estimatedMinutes: 90,
  },
  {
    id: '1C-4b',
    rank: 'First Class',
    category: 'NAVIGATION',
    number: '4b',
    description: 'Demonstrate how to use a handheld GPS unit, GPS app on a smartphone, or other electronic navigation system. Use GPS to find your current location, a destination of your choice, and the route you will take to get there. Follow that route to arrive at your destination.',
    activityTags: ['navigation', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 45,
  },

  // NATURE
  {
    id: '1C-5a',
    rank: 'First Class',
    category: 'NATURE',
    number: '5a',
    description: 'Identify or show evidence of at least 10 kinds of native plants found in your local area or campsite location. You may show evidence by identifying fallen leaves or fallen fruit that you find in the field, or as part of a collection you have made, or by photographs you have taken.',
    activityTags: ['nature'],
    setting: 'either',
    estimatedMinutes: 60,
  },
  {
    id: '1C-5b',
    rank: 'First Class',
    category: 'NATURE',
    number: '5b',
    description: 'Identify two ways to obtain a weather forecast for an upcoming activity. Explain why weather forecasts are important when planning for an event.',
    activityTags: ['nature', 'discussion', 'planning'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-5c',
    rank: 'First Class',
    category: 'NATURE',
    number: '5c',
    description: 'Describe at least three natural indicators of impending hazardous weather, the potential dangerous events that might result from such weather conditions, and the appropriate actions to take.',
    activityTags: ['nature', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-5d',
    rank: 'First Class',
    category: 'NATURE',
    number: '5d',
    description: 'Describe extreme weather conditions you might encounter in the outdoors in your local geographic area. Discuss how you would determine ahead of time the potential risk of these types of weather dangers, alternative planning considerations to avoid such risks, and how you would prepare for and respond to those weather conditions.',
    activityTags: ['nature', 'safety', 'discussion', 'planning'],
    setting: 'any',
    estimatedMinutes: 20,
  },

  // AQUATICS
  {
    id: '1C-6a',
    rank: 'First Class',
    category: 'AQUATICS',
    number: '6a',
    description: 'Successfully complete the BSA swimmer test.',
    activityTags: ['swimming', 'demonstration'],
    setting: 'campout',
    estimatedMinutes: 30,
  },
  {
    id: '1C-6b',
    rank: 'First Class',
    category: 'AQUATICS',
    number: '6b',
    description: 'Tell what precautions must be taken for a safe trip afloat.',
    activityTags: ['swimming', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-6c',
    rank: 'First Class',
    category: 'AQUATICS',
    number: '6c',
    description: 'Identify the basic parts of a canoe, kayak, or other boat. Identify the parts of a paddle or an oar.',
    activityTags: ['swimming', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-6d',
    rank: 'First Class',
    category: 'AQUATICS',
    number: '6d',
    description: 'Describe proper body positioning in a watercraft, depending on the type and size of the vessel. Explain the importance of proper body position in the boat.',
    activityTags: ['swimming', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-6e',
    rank: 'First Class',
    category: 'AQUATICS',
    number: '6e',
    description: 'With a helper and a practice victim, show a line rescue both as tender and as rescuer. (The practice victim should be approximately 30 feet from shore in deep water.)',
    activityTags: ['water-rescue', 'demonstration'],
    setting: 'campout',
    estimatedMinutes: 30,
  },

  // FIRST AID AND EMERGENCY PREPAREDNESS
  {
    id: '1C-7a',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7a',
    description: 'Demonstrate bandages for a sprained ankle and for injuries on the head, the upper arm, and the collarbone.',
    activityTags: ['first-aid', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 30,
  },
  {
    id: '1C-7b',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7b',
    description: 'By yourself and with a partner, show how to: Transport a person from a smoke-filled room. Transport for at least 25 yards a person with a sprained ankle.',
    activityTags: ['first-aid', 'emergency', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 30,
  },
  {
    id: '1C-7c',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7c',
    description: 'Tell the five most common signals of a heart attack. Explain the steps (procedures) in cardiopulmonary resuscitation (CPR).',
    activityTags: ['first-aid', 'emergency', 'discussion'],
    setting: 'any',
    estimatedMinutes: 20,
  },
  {
    id: '1C-7d',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7d',
    description: 'Tell what utility services exist in your home or meeting place. Describe potential hazards associated with these utilities and tell how to respond in emergency situations.',
    activityTags: ['emergency', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-7e',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7e',
    description: 'Develop an emergency action plan for your home that includes what to do in case of fire, storm, power outage, and water outage.',
    activityTags: ['emergency', 'planning'],
    setting: 'home',
    estimatedMinutes: 30,
  },
  {
    id: '1C-7f',
    rank: 'First Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '7f',
    description: 'Explain how to obtain potable water in an emergency.',
    activityTags: ['emergency', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },

  // FITNESS
  {
    id: '1C-8a',
    rank: 'First Class',
    category: 'FITNESS',
    number: '8a',
    description: 'After completing Second Class requirement 7a, be physically active at least 30 minutes each day for five days a week for four weeks. Keep track of your activities.',
    activityTags: ['fitness'],
    setting: 'home',
    estimatedMinutes: 0, // Tracked over time
  },
  {
    id: '1C-8b',
    rank: 'First Class',
    category: 'FITNESS',
    number: '8b',
    description: 'Share your challenges and successes in completing First Class requirement 8a. Set a goal for continuing to include physical activity as part of your daily life.',
    activityTags: ['fitness', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },

  // CITIZENSHIP
  {
    id: '1C-9a',
    rank: 'First Class',
    category: 'CITIZENSHIP',
    number: '9a',
    description: 'Visit and discuss with a selected individual approved by your leader (for example, an elected official, judge, attorney, civil servant, principal, or teacher) the constitutional rights and obligations of a U.S. citizen.',
    activityTags: ['citizenship', 'discussion'],
    setting: 'any',
    estimatedMinutes: 60,
  },
  {
    id: '1C-9b',
    rank: 'First Class',
    category: 'CITIZENSHIP',
    number: '9b',
    description: 'Investigate an environmental issue affecting your community. Share what you learned about that issue with your patrol or troop. Tell what, if anything, could be done by you or your community to address the concern.',
    activityTags: ['citizenship', 'nature', 'discussion'],
    setting: 'any',
    estimatedMinutes: 45,
  },
  {
    id: '1C-9c',
    rank: 'First Class',
    category: 'CITIZENSHIP',
    number: '9c',
    description: 'On a Scouting or family outing, take note of the trash and garbage you produce. Before your next similar outing, decide how you can reduce, recycle, or repurpose what you take on that outing, and then put those plans into action. Compare your results.',
    activityTags: ['citizenship', 'camping', 'planning'],
    setting: 'campout',
    estimatedMinutes: 30,
  },
  {
    id: '1C-9d',
    rank: 'First Class',
    category: 'CITIZENSHIP',
    number: '9d',
    description: 'Participate in three hours of service through one or more service projects approved by your Scoutmaster. The project(s) must not be the same service project(s) used for Tenderfoot requirement 7b and Second Class requirement 8e. Explain how your service to others relates to the Scout Law.',
    activityTags: ['service', 'citizenship'],
    setting: 'either',
    estimatedMinutes: 180,
  },

  // LEADERSHIP
  {
    id: '1C-10',
    rank: 'First Class',
    category: 'LEADERSHIP',
    number: '10',
    description: 'Tell someone who is eligible to join Scouts BSA, or an adult who may be interested in helping with the troop, about your Scouting activities. Invite them to an outing, activity, service project, or meeting. Provide information on how to join, or encourage the adult to register as a volunteer and give them the Scoutmaster\'s contact information.',
    activityTags: ['discussion'],
    setting: 'any',
    estimatedMinutes: 30,
  },

  // SCOUT SPIRIT
  {
    id: '1C-11',
    rank: 'First Class',
    category: 'SCOUT SPIRIT',
    number: '11',
    description: 'Demonstrate Scout spirit by living the Scout Oath and Scout Law. Tell how you have done your duty to God and how you have lived four different points of the Scout Law in your everyday life (different ones from prior ranks).',
    activityTags: ['discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '1C-12',
    rank: 'First Class',
    category: 'SCOUT SPIRIT',
    number: '12',
    description: 'While working toward the First Class rank, and after completing Second Class requirement 11, participate in a Scoutmaster conference.',
    activityTags: ['discussion'],
    setting: 'meeting',
    estimatedMinutes: 30,
  },
  {
    id: '1C-13',
    rank: 'First Class',
    category: 'SCOUT SPIRIT',
    number: '13',
    description: 'Successfully complete your board of review for the First Class rank.',
    activityTags: [],
    setting: 'meeting',
    estimatedMinutes: 30,
  },
];
