import { Requirement } from '../types.js';

export const secondClassRequirements: Requirement[] = [
  // CAMPING AND OUTDOOR ETHICS
  {
    id: '2C-1a',
    rank: 'Second Class',
    category: 'CAMPING AND OUTDOOR ETHICS',
    number: '1a',
    description: 'Since joining Scouts BSA, participate in five separate troop/patrol activities, at least three of which must be held outdoors. Of the outdoor activities, at least two must include overnight camping. These activities do not include troop or patrol meetings. On campouts, spend the night in a tent that you pitch or other structure that you help erect, such as a lean-to, snow cave, or tepee.',
    activityTags: ['camping'],
    setting: 'campout',
    estimatedMinutes: 0, // Tracked over time
  },
  {
    id: '2C-1b',
    rank: 'Second Class',
    category: 'CAMPING AND OUTDOOR ETHICS',
    number: '1b',
    description: 'Recite the principles of Leave No Trace from memory. Explain how you follow them on all outings.',
    activityTags: ['camping', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-1c',
    rank: 'Second Class',
    category: 'CAMPING AND OUTDOOR ETHICS',
    number: '1c',
    description: 'On one of these campouts, select a location for your patrol site and recommend it to your patrol leader, senior patrol leader, or troop guide. Explain what factors you should consider when choosing a patrol site and where to pitch a tent.',
    activityTags: ['camping', 'planning'],
    setting: 'campout',
    estimatedMinutes: 30,
  },

  // COOKING AND TOOLS
  {
    id: '2C-2a',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2a',
    description: 'Explain when it is appropriate to use a fire for cooking or other purposes and when it would not be appropriate to do so.',
    activityTags: ['cooking', 'fire-building', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-2b',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2b',
    description: 'Use a pocketknife, and a saw or axe if needed, to prepare tinder, kindling, and fuel wood for a cooking fire.',
    activityTags: ['tools', 'fire-building'],
    setting: 'campout',
    estimatedMinutes: 30,
  },
  {
    id: '2C-2c',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2c',
    description: 'Using a minimum-impact method at an approved outdoor location and time, use the tinder, kindling, and fuel wood from Second Class requirement 2b to demonstrate how to build a fire. Unless prohibited by local fire restrictions, light the fire. After allowing the flames to burn safely for at least two minutes, safely extinguish the flames with minimal impact to the fire site. Properly dispose of the ashes and any charred remains.',
    activityTags: ['fire-building', 'camping'],
    setting: 'campout',
    estimatedMinutes: 45,
  },
  {
    id: '2C-2d',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2d',
    description: 'Explain when it is appropriate to use a lightweight stove and when it is appropriate to use a propane stove. Set up a lightweight stove or propane stove. Light the stove, unless prohibited by local fire restrictions. Describe the safety procedures for using these types of stoves.',
    activityTags: ['stove', 'cooking', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 30,
  },
  {
    id: '2C-2e',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2e',
    description: 'On one campout, plan and cook one hot breakfast or lunch, selecting foods from MyPlate or the current USDA nutritional model. Explain the importance of good nutrition. Demonstrate how to transport, store, and prepare the foods you selected.',
    activityTags: ['cooking', 'planning'],
    setting: 'campout',
    estimatedMinutes: 90,
  },
  {
    id: '2C-2f',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2f',
    description: 'Demonstrate tying the sheet bend knot. Describe a situation in which you would use this knot.',
    activityTags: ['knots', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-2g',
    rank: 'Second Class',
    category: 'COOKING AND TOOLS',
    number: '2g',
    description: 'Demonstrate tying the bowline knot. Describe a situation in which you would use this knot.',
    activityTags: ['knots', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 15,
  },

  // NAVIGATION
  {
    id: '2C-3a',
    rank: 'Second Class',
    category: 'NAVIGATION',
    number: '3a',
    description: 'Demonstrate how a compass works and how to orient a map. Use a map to point out and tell the meaning of five map symbols.',
    activityTags: ['compass', 'map', 'navigation', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 30,
  },
  {
    id: '2C-3b',
    rank: 'Second Class',
    category: 'NAVIGATION',
    number: '3b',
    description: 'Using a compass and map together, take a 5-mile hike (or 10 miles by bike) approved by your adult leader and your parent or guardian.',
    activityTags: ['compass', 'map', 'hiking', 'navigation'],
    setting: 'campout',
    estimatedMinutes: 180,
  },
  {
    id: '2C-3c',
    rank: 'Second Class',
    category: 'NAVIGATION',
    number: '3c',
    description: 'Describe some hazards or injuries that you might encounter on your hike and what you can do to help prevent them.',
    activityTags: ['hiking', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-3d',
    rank: 'Second Class',
    category: 'NAVIGATION',
    number: '3d',
    description: 'Demonstrate how to find directions during the day and at night without using a compass or an electronic device.',
    activityTags: ['navigation', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 20,
  },

  // NATURE
  {
    id: '2C-4',
    rank: 'Second Class',
    category: 'NATURE',
    number: '4',
    description: 'Identify or show evidence of at least 10 kinds of wild animals (such as birds, mammals, reptiles, fish, or mollusks) found in your local area or camping location. You may show evidence by tracks, signs, or photographs you have taken.',
    activityTags: ['nature'],
    setting: 'either',
    estimatedMinutes: 60,
  },

  // AQUATICS
  {
    id: '2C-5a',
    rank: 'Second Class',
    category: 'AQUATICS',
    number: '5a',
    description: 'Tell what precautions must be taken for a safe swim.',
    activityTags: ['swimming', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-5b',
    rank: 'Second Class',
    category: 'AQUATICS',
    number: '5b',
    description: 'Demonstrate your ability to pass the BSA beginner test: Jump feetfirst into water over your head in depth, level off and swim 25 feet on the surface, stop, turn sharply, resume swimming, then return to your starting place.',
    activityTags: ['swimming', 'demonstration'],
    setting: 'campout', // Requires water access
    estimatedMinutes: 30,
  },
  {
    id: '2C-5c',
    rank: 'Second Class',
    category: 'AQUATICS',
    number: '5c',
    description: 'Demonstrate water rescue methods by reaching with your arm or leg, by reaching with a suitable object, and by throwing lines and objects.',
    activityTags: ['water-rescue', 'demonstration'],
    setting: 'either',
    estimatedMinutes: 30,
  },
  {
    id: '2C-5d',
    rank: 'Second Class',
    category: 'AQUATICS',
    number: '5d',
    description: 'Explain why swimming rescues should not be attempted when a reaching or throwing rescue is possible. Explain why and how a rescue swimmer should avoid contact with the victim.',
    activityTags: ['water-rescue', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },

  // FIRST AID AND EMERGENCY PREPAREDNESS
  {
    id: '2C-6a',
    rank: 'Second Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '6a',
    description: 'Demonstrate first aid for the following: Object in the eye, Bite of a warm-blooded animal, Puncture wounds from a splinter, nail, and fishhook, Serious burns (partial thickness, or second-degree), Heat exhaustion, Shock, Heatstroke, dehydration, hypothermia, and hyperventilation.',
    activityTags: ['first-aid', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 60,
  },
  {
    id: '2C-6b',
    rank: 'Second Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '6b',
    description: 'Show what to do for "hurry" cases of stopped breathing, stroke, severe bleeding, and ingested poisoning.',
    activityTags: ['first-aid', 'emergency', 'demonstration'],
    setting: 'any',
    estimatedMinutes: 30,
  },
  {
    id: '2C-6c',
    rank: 'Second Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '6c',
    description: 'Tell what you can do while on a campout or hike to prevent or reduce the occurrence of the injuries listed in Second Class requirements 6a and 6b.',
    activityTags: ['first-aid', 'safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-6d',
    rank: 'Second Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '6d',
    description: 'Explain what to do in case of accidents that require emergency response in the home and backcountry. Explain what constitutes an emergency and what information you will need to provide to a responder.',
    activityTags: ['emergency', 'discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-6e',
    rank: 'Second Class',
    category: 'FIRST AID AND EMERGENCY PREPAREDNESS',
    number: '6e',
    description: 'Tell how you should respond if you come upon the scene of a vehicular accident.',
    activityTags: ['emergency', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },

  // FITNESS
  {
    id: '2C-7a',
    rank: 'Second Class',
    category: 'FITNESS',
    number: '7a',
    description: 'After completing Tenderfoot requirement 6c, be physically active at least 30 minutes each day for five days a week for four weeks. Keep track of your activities.',
    activityTags: ['fitness'],
    setting: 'home',
    estimatedMinutes: 0, // Tracked over time
  },
  {
    id: '2C-7b',
    rank: 'Second Class',
    category: 'FITNESS',
    number: '7b',
    description: 'Share your challenges and successes in completing Second Class requirement 7a. Set a goal for continuing to include physical activity as part of your daily life and develop a plan for doing so.',
    activityTags: ['fitness', 'discussion', 'planning'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-7c',
    rank: 'Second Class',
    category: 'FITNESS',
    number: '7c',
    description: 'Participate in a school, community, or troop program on the dangers of using drugs, alcohol, and tobacco and other practices that could be harmful to your health. Discuss your participation in the program with your family, and explain the dangers of substance addictions. Report to your Scoutmaster or other adult leader in your troop about which parts of the Scout Oath and Scout Law relate to what you learned.',
    activityTags: ['safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 60,
  },

  // CITIZENSHIP
  {
    id: '2C-8a',
    rank: 'Second Class',
    category: 'CITIZENSHIP',
    number: '8a',
    description: 'Participate in a flag ceremony for your school, religious institution, chartered organization, community, or Scouting activity.',
    activityTags: ['flag-ceremony', 'citizenship'],
    setting: 'either',
    estimatedMinutes: 15,
  },
  {
    id: '2C-8b',
    rank: 'Second Class',
    category: 'CITIZENSHIP',
    number: '8b',
    description: 'Explain what respect is due the flag of the United States.',
    activityTags: ['citizenship', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },
  {
    id: '2C-8c',
    rank: 'Second Class',
    category: 'CITIZENSHIP',
    number: '8c',
    description: 'With your parents or guardian, decide on an amount of money that you would like to earn, based on the cost of a specific item you would like to purchase. Develop a written plan to earn the amount agreed upon and follow that plan; it is acceptable to make changes to your plan along the way. Discuss any changes made to your original plan and whether you met your goal.',
    activityTags: ['citizenship', 'planning'],
    setting: 'home',
    estimatedMinutes: 0, // Tracked over time
  },
  {
    id: '2C-8d',
    rank: 'Second Class',
    category: 'CITIZENSHIP',
    number: '8d',
    description: 'At a minimum of three locations, compare the cost of the item for which you are saving to determine the best place to purchase it. After completing Second Class requirement 8c, decide if you will use the amount that you earned as originally intended, save all or part of it, or use it for another purpose.',
    activityTags: ['citizenship', 'planning'],
    setting: 'home',
    estimatedMinutes: 0, // Done at home
  },
  {
    id: '2C-8e',
    rank: 'Second Class',
    category: 'CITIZENSHIP',
    number: '8e',
    description: 'Participate in two hours of service through one or more service projects approved by your Scoutmaster. Tell how your service to others relates to the Scout Oath.',
    activityTags: ['service', 'citizenship'],
    setting: 'either',
    estimatedMinutes: 120,
  },

  // PERSONAL SAFETY AWARENESS
  {
    id: '2C-9a',
    rank: 'Second Class',
    category: 'PERSONAL SAFETY AWARENESS',
    number: '9a',
    description: 'Explain the three R\'s of personal safety and protection.',
    activityTags: ['safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },
  {
    id: '2C-9b',
    rank: 'Second Class',
    category: 'PERSONAL SAFETY AWARENESS',
    number: '9b',
    description: 'Describe bullying; tell what the appropriate response is to someone who is bullying you or another person.',
    activityTags: ['safety', 'discussion'],
    setting: 'any',
    estimatedMinutes: 10,
  },

  // SCOUT SPIRIT
  {
    id: '2C-10',
    rank: 'Second Class',
    category: 'SCOUT SPIRIT',
    number: '10',
    description: 'Demonstrate Scout spirit by living the Scout Oath and Scout Law. Tell how you have done your duty to God and how you have lived four different points of the Scout Law (not to include those used for Tenderfoot requirement 9) in your everyday life.',
    activityTags: ['discussion'],
    setting: 'any',
    estimatedMinutes: 15,
  },
  {
    id: '2C-11',
    rank: 'Second Class',
    category: 'SCOUT SPIRIT',
    number: '11',
    description: 'While working toward the Second Class rank, and after completing Tenderfoot requirement 10, participate in a Scoutmaster conference.',
    activityTags: ['discussion'],
    setting: 'meeting',
    estimatedMinutes: 30,
  },
  {
    id: '2C-12',
    rank: 'Second Class',
    category: 'SCOUT SPIRIT',
    number: '12',
    description: 'Successfully complete your board of review for the Second Class rank.',
    activityTags: [],
    setting: 'meeting',
    estimatedMinutes: 30,
  },
];
